# Generated by Django 5.1.4 on 2025-07-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Published',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('link', models.URLField()),
                ('authors', models.ManyToManyField(related_name='news', to='myapp.author')),
                ('published_dates', models.ManyToManyField(related_name='news', to='myapp.published')),
            ],
        ),
    ]
